table 'AW_Product_Categories (dim)'
	lineageTag: 8404407e-ebee-4759-ab70-2bce7715bd0c

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: f32ab508-9c0f-4133-bad9-cd8ad2f3185f
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: eccdc8a2-aba0-4f0a-8f9b-621c737b7d6e
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'AW_Product_Categories (dim)-76ffe5b6-c2cd-4543-8e56-f293ed452a26' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\POWER BI Class\AdventureWorks CSV Files\AdventureWorks_Product_Categories.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

