table AW_Sales_2016
	isHidden
	lineageTag: c9f24571-fae6-4bc2-9d5e-67b69f402354

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 97e16ea4-7374-4302-8021-acff2f49070a
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 5252b27e-a8b2-42b6-9398-0068f421e3ce
			defaultHierarchy: LocalDateTable_613cdf2d-2ebc-41a3-b926-3b625cdc45db.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 0cc1bae8-7f50-4517-ad90-b693c0b7d223
		summarizeBy: none
		sourceColumn: StockDate

		variation Variation
			isDefault
			relationship: 4e9dabfe-1402-4cc6-87e6-ed357ee333cc
			defaultHierarchy: LocalDateTable_300c7e0d-fe7f-49f9-96ff-5bb01ed1a97b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		isHidden
		lineageTag: a2a93095-0be2-4b0c-9035-e1757cc5626b
		summarizeBy: none
		sourceColumn: OrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f0b9b67e-5377-462b-b21d-898329f44c96
		summarizeBy: count
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 73bca5b0-bb31-4aa5-9399-e1970da1ef94
		summarizeBy: count
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aad9fe54-ce79-450f-b8ed-b0327a8db952
		summarizeBy: count
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b8e1a86e-8fc3-424a-8505-32cd88193407
		summarizeBy: sum
		sourceColumn: OrderLineItem

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b44e9d00-d50d-44ab-a7f5-c956d362ec4f
		summarizeBy: sum
		sourceColumn: OrderQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition AW_Sales_2016-8422b573-a71d-4517-9324-b857ce09be48 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\POWER BI Class\AdventureWorks CSV Files\AdventureWorks_Sales_2016.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

